//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VbeComponents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VbeComponents.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VBE Component manager add-in could not be loaded!
        ///{0}.
        /// </summary>
        internal static string AddInCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("AddInCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create VBE Components manager menu!
        ///Please review the error message.
        ///{0}.
        /// </summary>
        internal static string AddInMenuCouldNotBeCreated {
            get {
                return ResourceManager.GetString("AddInMenuCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBE Components manager.
        /// </summary>
        internal static string ApplicationMessageCaption {
            get {
                return ResourceManager.GetString("ApplicationMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance of the configuration file cannot be null.
        /// </summary>
        internal static string ConfigIsNull {
            get {
                return ResourceManager.GetString("ConfigIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify path to export.
        /// </summary>
        internal static string DefaultPathValue {
            get {
                return ResourceManager.GetString("DefaultPathValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components in the project.
        /// </summary>
        internal static string ExceptionNoComponents {
            get {
                return ResourceManager.GetString("ExceptionNoComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components could not be exported. 
        ///A COM exception was thrown: {0}&quot;.
        /// </summary>
        internal static string ExportComExceptionText {
            get {
                return ResourceManager.GetString("ExportComExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to export {0} {1}
        ///Are you sure?.
        /// </summary>
        internal static string ExportConfirmation {
            get {
                return ResourceManager.GetString("ExportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export project components.
        /// </summary>
        internal static string ExportFormMessageCaption {
            get {
                return ResourceManager.GetString("ExportFormMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one component to export!.
        /// </summary>
        internal static string ExportNoItemSelected {
            get {
                return ResourceManager.GetString("ExportNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path doesn&apos;t exists!
        ///{0}.
        /// </summary>
        internal static string FolderDoesnExists {
            get {
                return ResourceManager.GetString("FolderDoesnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a folder.
        /// </summary>
        internal static string ImportAddFolder {
            get {
                return ResourceManager.GetString("ImportAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to import {0} {1}
        ///Are you sure?.
        /// </summary>
        internal static string ImportConfirmation {
            get {
                return ResourceManager.GetString("ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import components.
        /// </summary>
        internal static string ImportFormMessageCaption {
            get {
                return ResourceManager.GetString("ImportFormMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one component to import!.
        /// </summary>
        internal static string ImportNoItemSelected {
            get {
                return ResourceManager.GetString("ImportNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder doesn&apos;t have any valid VBA component!.
        /// </summary>
        internal static string InvalidComponentFolder {
            get {
                return ResourceManager.GetString("InvalidComponentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of components: {0} ({1} selected).
        /// </summary>
        internal static string NumberOfComponentsPlusSelected {
            get {
                return ResourceManager.GetString("NumberOfComponentsPlusSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path is not valid!
        ///Please correct..
        /// </summary>
        internal static string PathIsNotValid {
            get {
                return ResourceManager.GetString("PathIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (valid, {0} components).
        /// </summary>
        internal static string ProjectValidated {
            get {
                return ResourceManager.GetString("ProjectValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (validating...).
        /// </summary>
        internal static string ProjectValidating {
            get {
                return ResourceManager.GetString("ProjectValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project &apos;{0}&apos; is protected.
        ///You cannot import/export anything to protected projects..
        /// </summary>
        internal static string ProtectedProject {
            get {
                return ResourceManager.GetString("ProtectedProject", resourceCulture);
            }
        }
    }
}
